// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbouvzsvdnwnjtuynvjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZib3V2enN2ZG53bmp0dXludmprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTg1MzIsImV4cCI6MjA1NDg3NDUzMn0.k9UCDCZ8eqTSTV9optyn-D5wEVUdQ0ht2pg2-sM1tc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);